version: '3.9'

services:

  backend:
    build: .
    container_name: fsb_backend

    ports:
      - "8000:8000"

    env_file:
      - .env

    depends_on:
      - db
      - redis

    volumes:
      - .:/app

  db:
    image: postgres:16

    container_name: fsb_postgres

    restart: always

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: fsb_db

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7

    container_name: fsb_redis

    ports:
      - "6379:6379"

  celery:
    build: .

    container_name: fsb_celery

    command: celery -A fsbsrc.core.celery_app.celery worker --loglevel=info

    env_file:
      - .env

    depends_on:
      - redis
      - db

volumes:
  postgres_data: